# Generated by Django 2.2.24 on 2022-12-08 16:32

import phonenumbers
from django.db import migrations


def clear_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all().iterator()
    for flat in flats:
        pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_possible_number(pure_phonenumber) and phonenumbers.is_valid_number(pure_phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(pure_phonenumber, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owner_pure_phone = ''
        flat.save()


def move_backwards(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all().iterator()
    for flat in flats:
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(clear_phonenumbers, move_backwards)
    ]