# Generated by Django 2.2.24 on 2022-12-08 21:51

from django.db import migrations


def clear_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)


def move_backwards(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(clear_phonenumbers, move_backwards)
    ]
